model:
  id: <YOUR_MODEL_ID>
  user_id: <YOUR_USER_ID>
  app_id: <YOUR_APP_ID>
  model_type_id: text-to-text
build_info:
  python_version: '3.11'
inference_compute_info:
  cpu_limit: '8'
  cpu_memory: 10Gi
  num_accelerators: 1
  accelerator_type:
  - NVIDIA-*
  accelerator_memory: 12Gi
num_threads: 128
checkpoints:
  type: huggingface
  repo_id: unsloth/Qwen3-0.6B
  when: runtime
