model:
  id: image-classifier-model
  user_id: placeholder_user
  app_id: placeholder_app
  model_type_id: visual-classifier
build_info:
  python_version: '3.11'
inference_compute_info:
  cpu_limit: '4'
  cpu_memory: 8Gi
  num_accelerators: 1
  accelerator_type:
  - NVIDIA-*
  accelerator_memory: 2Gi
concepts:
- id: '0'
  name: placeholder
